# stage_assets.ps1
# Stage Chromium kernels + optional proxy/helper assets to C:\Temp\BB_dist,
# then generate build/windows/installer/bb_files.nsh with explicit NSIS File lines.
#
# Standard local layout:
#   <BOOST_KERNEL_SRC or repo root>\chrome\cloak-146.0.7680.177\chrome.exe   REQUIRED
#   <BOOST_KERNEL_SRC or repo root>\chrome\google-148.0.7778.167\chrome.exe  OPTIONAL Chrome for Testing
#   <BOOST_KERNEL_SRC or repo root>\bin\                                      OPTIONAL proxy tools
#   <BOOST_KERNEL_SRC or repo root>\extensions\chromium-web-store\            OPTIONAL helper extension
#
# If the helper extension is missing from BOOST_KERNEL_SRC, this script falls
# back to backend\embedded_extensions\chromium-web-store from the repo.

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$StageRoot = "C:\Temp\BB_dist"
$NshFile   = "$RepoRoot\build\windows\installer\bb_files.nsh"
$AssetRoot = if ($env:BOOST_KERNEL_SRC) { $env:BOOST_KERNEL_SRC } else { $RepoRoot }

$RequiredKernels = @("cloak-146.0.7680.177")
$OptionalKernels = @("google-148.0.7778.167")

function Copy-Tree([string]$src, [string]$dst, [string]$Label, [bool]$Required) {
    if (-not (Test-Path $src)) {
        if ($Required) { throw "required asset not found: $src" }
        Write-Host "    optional missing, skip: $Label ($src)" -ForegroundColor Yellow
        return $false
    }
    Write-Host "    $Label ..." -ForegroundColor Gray
    New-Item -ItemType Directory -Force -Path $dst | Out-Null
    robocopy $src $dst /E /NFL /NDL /NJH /NJS /NP | Out-Null
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed (exit=$LASTEXITCODE) $src -> $dst" }
    return $true
}

Write-Host "==> Stage assets to $StageRoot" -ForegroundColor Cyan
Write-Host "    asset root: $AssetRoot" -ForegroundColor Gray

if (Test-Path $StageRoot) {
    Write-Host "    cleaning old stage dir ..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force $StageRoot
}
New-Item -ItemType Directory -Force -Path $StageRoot | Out-Null
New-Item -ItemType Directory -Force -Path "$StageRoot\chrome" | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $NshFile) | Out-Null

foreach ($k in $RequiredKernels) {
    $src = "$AssetRoot\chrome\$k"
    $dst = "$StageRoot\chrome\$k"
    Copy-Tree $src $dst "chrome\$k (required)" $true | Out-Null
    if (-not (Test-Path "$dst\chrome.exe")) { throw "required chrome.exe missing after staging: $dst\chrome.exe" }
}

foreach ($k in $OptionalKernels) {
    $src = "$AssetRoot\chrome\$k"
    $dst = "$StageRoot\chrome\$k"
    $compatMarker = Join-Path $src "chrome-for-testing.marker"
    if ((Test-Path (Join-Path $src "chrome.exe")) -and (Test-Path $compatMarker)) {
        Copy-Tree $src $dst "chrome\$k (optional Chrome for Testing)" $false | Out-Null
    } elseif (Test-Path $src) {
        Write-Host "    skip incompatible official Chrome kernel: $src" -ForegroundColor Yellow
    }
}

Copy-Tree "$AssetRoot\bin" "$StageRoot\bin" "bin\ proxy tools (optional)" $false | Out-Null

$extensionSource = "$AssetRoot\extensions\chromium-web-store"
if (-not (Test-Path $extensionSource)) {
    $extensionSource = "$RepoRoot\backend\embedded_extensions\chromium-web-store"
}
Copy-Tree $extensionSource "$StageRoot\extensions\chromium-web-store" "extensions\chromium-web-store (optional)" $false | Out-Null

Write-Host "    top-level files ..." -ForegroundColor Gray
$looseFiles = @(
    @{ Source = "$AssetRoot\app.ico"; Destination = "$StageRoot\app.ico"; Required = $false },
    @{ Source = "$AssetRoot\app.png"; Destination = "$StageRoot\app.png"; Required = $false },
    @{ Source = "$RepoRoot\build\windows\icon.ico"; Destination = "$StageRoot\app.ico"; Required = $false },
    @{ Source = "$RepoRoot\build\appicon.png"; Destination = "$StageRoot\app.png"; Required = $false },
    @{ Source = "$AssetRoot\.boost-license.json"; Destination = "$StageRoot\.boost-license.json"; Required = $false }
)
foreach ($item in $looseFiles) {
    if ((Test-Path $item.Source) -and -not (Test-Path $item.Destination)) {
        Copy-Item $item.Source $item.Destination -Force
    }
}

$totalSize = (Get-ChildItem $StageRoot -Recurse -File | Measure-Object Length -Sum).Sum
$totalFiles = (Get-ChildItem $StageRoot -Recurse -File).Count
Write-Host ("==> Stage done: {0} files, {1:N0} MB" -f $totalFiles, ($totalSize/1MB)) -ForegroundColor Green

# ============================================================
# Generate bb_files.nsh - explicit File enumeration
# ============================================================
Write-Host "==> Generating $NshFile" -ForegroundColor Cyan

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("; Auto-generated - do not edit by hand")
$lines.Add("; Generated by scripts\stage_assets.ps1")
$lines.Add("; Stage source: $StageRoot")
$lines.Add("")
$lines.Add("!macro bb.bundleAssets")

$allFiles = Get-ChildItem $StageRoot -Recurse -File
$grouped = $allFiles | Group-Object { $_.DirectoryName }

$rootFiles = $allFiles | Where-Object { $_.DirectoryName -eq $StageRoot }
if ($rootFiles) {
    $lines.Add('    SetOutPath "$INSTDIR"')
    foreach ($f in $rootFiles) { $lines.Add('    File "' + $f.FullName + '"') }
}

foreach ($g in $grouped | Sort-Object Name) {
    if ($g.Name -eq $StageRoot) { continue }
    $relDir = $g.Name.Substring($StageRoot.Length).TrimStart('\')
    $nsisDir = '$INSTDIR\' + $relDir
    $lines.Add('    SetOutPath "' + $nsisDir + '"')
    foreach ($f in $g.Group) { $lines.Add('    File "' + $f.FullName + '"') }
}

$lines.Add("!macroend")
[System.IO.File]::WriteAllLines($NshFile, $lines, [System.Text.Encoding]::ASCII)

$nshLines = (Get-Content $NshFile).Count
Write-Host ("    -> bb_files.nsh ({0} lines, {1} File entries)" -f $nshLines, $allFiles.Count) -ForegroundColor Green
